export { Resource } from './resource.entity'
export { ResourceItem } from './resource-item.entity'
export { Publication } from './publication.entity'
export { Author } from './author.entity'
export { Character } from './character.entity'
