import { ArrowRightIcon } from '@chakra-ui/icons'
import { Heading, HStack, Stack, Text } from '@chakra-ui/react'
import { ColorModeSwitch, CoolButtonLink } from 'components'
import type { NextPage } from 'next'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'

export async function getStaticProps({ locale }: { locale: string }) {
	return {
		props: await serverSideTranslations(locale, ['index', 'common']),
	}
}

const Home: NextPage = () => {
	const { t } = useTranslation(['index', 'common'])

	return (
		<>
			<Head>
				<title>Publication Storage System</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Stack minH="90vh" p={6}>
				<HStack justify="flex-end">
					<ColorModeSwitch />
				</HStack>
				<Stack textAlign="center" spacing={12} flexGrow={1} justify="center">
					<Heading
						as="h1"
						fontSize={{
							base: '5xl',
							lg: '6xl',
							xl: '7xl',
						}}
						lineHeight="base"
						py={2}
					>
						{t('welcome')}
						<br />
						<Text as="span" color="primary.500">
							{t('title', { ns: 'common' })}
						</Text>
					</Heading>
					<div>
						<CoolButtonLink to="/about" rightIcon={<ArrowRightIcon w={3} />}>
							{t('button')}
						</CoolButtonLink>
					</div>
					<div>
						<Text fontSize="md" color="text.secondary" maxW="md" m="auto">
							{t('description')}
						</Text>
					</div>
				</Stack>
			</Stack>
		</>
	)
}

export default Home
