export { default as Delay } from './Delay'
export { default as Lazy } from './Lazy'
export { default as Loader } from './Loader'
export { default as MainArea } from './MainArea'
export { default as Title } from './Title'
